# Generated by Django 5.2 on 2025-04-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_especialidade_profissional_delete_professional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='especialidade',
            new_name='specialty',
        ),
    ]
